configuration: Release

version: 1.0.{build}

image: Visual Studio 2017 RC

build:
    parallel: true
    publish_nuget: true
    verbosity: minimal

before_build:
  - dotnet restore
  
branches:
    only:
      - master

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
