configuration: Release

version: 1.0.{build}

image: Visual Studio 2017 RC

build:
    parallel: true
    publish_nuget: true
    verbosity: minimal

before_build:
  - dotnet restore
  
branches:
    only:
      - master
